### ISSUE TITLE
question about QVTKOpenGLWidget 

### ISSUE THREAD

**Issue by simonryu** [martijnkoopman/Qt-VTK-viewer#3]
Dear Martijn,

Thank you for your help. I am sorry to forget to ask additional questions before you close the issue. My question is as follows.

Did you copy "libQVTKWidgetPlugin.so" to the subfolder ".../plugins/designer/" of Qt install folder so that QVTKOpenGLWidget could be used?
Otherwise, If you did not use the QVTKWidgetPlugin, how could you make the class SceneWidget? (It seems that the codes related to SceneWidget are generated from Qt Creator just like the codes of the class MainWindow.)

 I copied libQVTKWidgetPlugin.so to  ".../plugins/designer/" but my Qt Designer could not load the plugin as shown in the figure below.
(The installer also automatically copied the same file to "/usr/local/plugins/designer/".)

![image](https://user-images.githubusercontent.com/9817432/44319150-fcd85e00-a474-11e8-9e58-5532f12a0548.png)

However,  I could run the program Qt-VTK-viewer on Ubuntu 16.04 after I successfully configured the cmake project of Qt-VTK-viewer.

I also tested the same things on the Windows 10 but I failed in configuring the cmake project even though my Qt Creator Kid is correctly set up.

![image](https://user-images.githubusercontent.com/9817432/44321336-60b55380-a482-11e8-9658-77a2b5d2c852.png)

Of course, my Qt Creator could not load QVTKWidgetPlugin on this Windows 10 platform.

(The installer also automatically copied "QVTKWidgetPlugin.dll" to "...\plugins\designer\" the subfolder of VTK install foler.)

![image](https://user-images.githubusercontent.com/9817432/44321242-d10fa500-a481-11e8-9d62-dc9052c6b427.png)

**Comment by martijnkoopman** [comment]
Hi Simonryu,

QVTKWidgetPlugin is not required for building the application. In fact, it is not used by Qt-VTK-Viewer at all.
As far as I know it is merely an extension of Qt Creator that enables the user to drag a QVTKOpenGLWidget into a form in Qt Designer.

The SceneWidget is added to the MainWindow by promoting a QOpenGLWidget. This works because the base class of QVTKOpenGLWidget is a QOpenGLWidget and because SceneWidget extends QVTKOpenGLWidget.

![promoted_widget](https://user-images.githubusercontent.com/15292384/44368668-e31a3380-a4d3-11e8-9773-5eba01b4a8aa.png)

More info about promoting widgets: http://doc.qt.io/qt-5/designer-using-custom-widgets.html

**Comment by simonryu** [comment]
Thank you for your kind reply and information!

**Comment by simonryu** [comment]
Thank you for your kind reply and information! This is the first time for me to use both Qt and VTK. Your comment is very helpful.

Dear martijnkoopman

I successfully added the SceneWidget to the MainWindow by promoting a QOpenGLWidget. And I also added header and source files of SceneWidget using the menu "add new C++ class" as the figure below.

![image](https://user-images.githubusercontent.com/9817432/44437380-ff61c180-a5f4-11e8-9dd9-a71ab6cbc879.png)
