### ISSUE TITLE
Additional question about the last comment on  issue #3

### ISSUE THREAD

**Issue by simonryu** [martijnkoopman/Qt-VTK-viewer#4]
I posted the same comment below after I closed the issue #3 . Since I am not sure that that comment could reach you, I am posting this issue again. When you answer to the comment, I will close or delete this issue.

----

Thank you for your kind reply and information! This is the first time for me to use both Qt and VTK. Your comment is very helpful.

I have one question about your last comment.
I successfully added the SceneWidget to the MainWindow by promoting a QOpenGLWidget. And I also added header and source files of SceneWidget using the menu "add new C++ class" as the figure below.
(Currently, I made a project for my application and tried to use SceneWidget class in my project.)

![image](https://user-images.githubusercontent.com/9817432/44437692-4d2af980-a5f6-11e8-948e-76dd37477687.png)

Then, I could see header and source file of SceneWidget class which has only a constructor without any other members. So, I copied the codes of SceneWidget in your project in order to use that.

Am I following up you correctly? The reason why I am raising this question: It seemed to me that header and source file of SceneWidget in your project would be automatically generated by Qt Creator. Did I miss anything else?

**Comment by martijnkoopman** [comment]
Hi Simonryu,

The SceneWidget class is not generated by itself.
By using "Add new C++ class" you generated the new header and cpp files.

What is generated however, is ui_mainwindow.h. It is generated from mainwindow.ui by the Qt User Interface Compiler (UIC) whenever you build the project. You can find this file in the build directory of your project.

In this file you will find the following statements:

`#include "scenewidget.h"`

This statement is present because you promoted a widget to a SceneWidget. In that process you had to define a header file. This should be the header file of the SceneWidget that you created before with "Add new C++ Class".
```
SceneWidget *sceneWidget;
...
sceneWidget = new SceneWidget(centralwidget);
sceneWidget->setObjectName(QStringLiteral("sceneWidget"));
gridLayout->addWidget(sceneWidget, 0, 0, 1, 1);
```
These statements are present because a SceneWidget has been added to the form. Probably by dragging a QOpenGLWidget to the canvas and then promoting it to a SceneWidget.

`QObject::connect(actionZoomToExtent, SIGNAL(triggered()), sceneWidget, SLOT(zoomToExtent()));`

This statement is present because certain signals and slots are defined in Qt Designer. This particular statement connects the signal triggered() of QAction actionZoomExtent to the slot zoomToExtent() of the QObject SceneWidget.

I hope this gives you some clarity.

**Comment by simonryu** [comment]
Dear martijnkoopman,
I did the followings.

1) made a new project with Qt Widgets Application

2) added new C++ class SceneWidget with base class QVTKOpenGLWidget
2-a. added the following five lines to .pro file (Qt Creator project file).
unix:!macx: LIBS += -L$$PWD/../../../usr/local/lib/ -lvtkGUISupportQt-8.1
unix:!macx: LIBS += -L$$PWD/../../../usr/local/lib/ -lvtkGUISupportQtOpenGL-8.1
unix:!macx: LIBS += -L$$PWD/../../../usr/local/lib/ -lvtkGUISupportQtSQL-8.1
INCLUDEPATH += $$PWD/../../../usr/local/include/vtk-8.1
DEPENDPATH  += $$PWD/../../../usr/local/include/vtk-8.1

2-b. added the following line to secenWidget.h file
#include <QVTKOpenGLWidget.h>

3) prompted SceneWidget class with base class QOpenGLWidget

4) Then built and ran and got the following message

![image](https://user-images.githubusercontent.com/9817432/44472556-5e611e00-a669-11e8-80b2-ffbb8ef5fc38.png)

5) So, I added the following constructor to SceneWidget class

![image](https://user-images.githubusercontent.com/9817432/44472649-8a7c9f00-a669-11e8-964d-6fb3a4ecc4bc.png)

6) Built and ran again and got the result below.

![image](https://user-images.githubusercontent.com/9817432/44472730-b566f300-a669-11e8-855a-9e11d8ef5507.png)

My question is as follows:
Q1) Was I correctly understand your comment?
Q2) If so, should I manually write the other member data and functions in your SceneWidget class such as code snippet below except  "zoomToExtent()"?

class SceneWidget : public QVTKOpenGLWidget
{
  Q_OBJECT
public:
  explicit SceneWidget(QWidget *parent = 0);

  //! Add a data set to the scene
  /*!
    \param[in] dataSet The data set to add
  */
  void addDataSet(vtkSmartPointer<vtkDataSet> dataSet);

  //! Remove the data set from the scene
  void removeDataSet();

public slots:
  //! Zoom to the extent of the data set in the scene
  void zoomToExtent();

private:
  vtkSmartPointer<vtkRenderer> m_renderer;
};

**Comment by martijnkoopman** [comment]
Hi Simonryu,

What are you exactly trying to achieve?
Recreate this project to learn how it is constructed?
Or change the build system from CMake to qmake? (Since you now created a new qmake project)
You can ofcourse simply use this project as a template and start adding functionalities from there on.

Anyhow, indeed you still have to implement some code in SceneWidget.
For example, in the constructor you should instantiate a vtkRenderWindow and a vtkRenderer.
That is why your view is currently black.
Next to that, to be neat, the constructor should also call its parent class constructor.

Also the following line should be added before you construct the QApplication:
`QSurfaceFormat::setDefaultFormat(QVTKOpenGLWidget::defaultFormat());`

More info: https://www.vtk.org/doc/nightly/html/classQVTKOpenGLWidget.html#details

Regards,
Martijn

**Comment by simonryu** [comment]
Dear Martijnkoopman,

Thank you for your kind reply and information.

My objective is to make an appliation which uses both my library and SceneWidget class. I do not understand the reason why your cmake project is not modified (I failed in adding my library to your project). For this purpose, I had to make a new qmake project.

I was not trying to ask you about what am I supposed to do with the black window. I jsut wanted to show what I did and my intermediate result in order to check out whether I correctly did what I should do as you advise. I understand that I should write some more code for SceneWidget class.

Thank you again!
Best,
Joonghyun
