### ISSUE TITLE
no "renderVTK"

### ISSUE THREAD

**Issue by fourteen14fourteen** [martijnkoopman/Qt-VTK-viewer#6]
when i build the peoject, Thefollowing happend:
D:\studydata\hosptial\qt\Qt-VTK-viewer-master\scenewidget.cpp:41: error: C3861: “renderVTK”: The identifier cannot be found

**Comment by martijnkoopman** [comment]
What version of VTK and Qt are you using? And what platform?

**Comment by fourteen14fourteen** [comment]
Win 10 +qt4.7.1+vtk8.2

**Comment by fourteen14fourteen** [comment]
can i cmake the file and then open in vs?

**Comment by martijnkoopman** [comment]
I see that the implementation of QVTKOpenGLWidget has been changed (commit: https://github.com/Kitware/VTK/commit/693fdeecaf2f2bf2352baade3443aab87df464ad#diff-5c79669acceafbd2343818e618770f70)
You should now use `paintGL()` instead of `renderVTK()`

I also think that perhaps `QVTKOpenGLNativeWidget `should be used instead.

I'll update this repository when I have time.

Also, be aware that support for Qt4 has been removed in version 8.2 of VTK. (See release notes: https://blog.kitware.com/vtk-8-2-0/)

Regarding your last question.  Yes, you can run CMake, generate a Visual Studio project and then build it with Visual Studio.

**Comment by Vishnu-C** [comment]
@martijnkoopman  Happen to update this repository?
Thanks

**Comment by martijnkoopman** [comment]
@Vishnu-C Done
